import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { DEMO_WORKSPACE_ID } from "@/lib/demo";
import { MasterDataValidationError, normalizeEmployee } from "@/lib/master-data";
import { assertMasterCanDelete, assertMasterCanRename } from "@/lib/master-data-references";
import { apiError, publicRow } from "@/lib/master-data-server";
type Ctx = { params: Promise<{ code: string }> };
async function employeeData(input: ReturnType<typeof normalizeEmployee>) { const { departmentCode, ...data } = input; if (!departmentCode) return { ...data, departmentId: null }; const department = await prisma.department.findUnique({ where: { workspaceId_code: { workspaceId: DEMO_WORKSPACE_ID, code: departmentCode } } }); if (!department) throw new MasterDataValidationError("Department not found"); return { ...data, departmentId: department.id }; }
function rowWithDepartment(row: { department: { code: string; name: string } | null } & Record<string, unknown>) { const { department, ...employee } = row; return { ...publicRow(employee), departmentCode: department?.code, departmentName: department?.name }; }
export async function PUT(req: Request, ctx: Ctx) { try { const { code } = await ctx.params; const oldCode = decodeURIComponent(code).toUpperCase(); const existing = await prisma.employee.findUnique({ where: { workspaceId_code: { workspaceId: DEMO_WORKSPACE_ID, code: oldCode } } }); if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 }); const data = normalizeEmployee(await req.json()); await assertMasterCanRename("employee", DEMO_WORKSPACE_ID, oldCode, data.code); const row = await prisma.employee.update({ where: { id: existing.id }, data: await employeeData(data), include: { department: true } }); return NextResponse.json(rowWithDepartment(row)); } catch (error) { return apiError(error, "Failed to update employee"); } }
export async function DELETE(_req: Request, ctx: Ctx) { try { const { code } = await ctx.params; const employeeCode = decodeURIComponent(code).toUpperCase(); const existing = await prisma.employee.findUnique({ where: { workspaceId_code: { workspaceId: DEMO_WORKSPACE_ID, code: employeeCode } } }); if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 }); await assertMasterCanDelete("employee", DEMO_WORKSPACE_ID, employeeCode); await prisma.employee.delete({ where: { id: existing.id } }); return NextResponse.json({ ok: true }); } catch (error) { return apiError(error, "Failed to delete employee"); } }
