"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { deleteQuotation, fetchQuotation, saveQuotation, TAX_TYPE_OPTIONS, CURRENCY_OPTIONS, type Quotation, type QuotationInput, type QuotationLine, type QuotationStatus, updateQuotationStatus } from "@/lib/quotations";
import { masterDataRequest } from "@/lib/master-data-client";

type MasterRow = { code: string; name: string; spec?: string; unit?: string; outboundPrice?: number };
type Props = { id?: string };
const today = () => new Date().toISOString().slice(0, 10);
const emptyLine = (index = 0): QuotationLine => ({ itemCode: "", itemName: "", spec: "", unit: "", qty: 1, unitPrice: 0, supply: 0, vat: 0, total: 0, extra: "", sortOrder: index });

export function QuotationForm({ id }: Props) {
  const router = useRouter(); const edit = Boolean(id);
  const [vendors, setVendors] = useState<MasterRow[]>([]); const [employees, setEmployees] = useState<MasterRow[]>([]); const [items, setItems] = useState<MasterRow[]>([]);
  const [header, setHeader] = useState({ quoteDate: today(), slipNo: "", vendorCode: "", vendorName: "", managerCode: "", managerName: "", validUntil: "", status: "draft" as QuotationStatus, taxType: "과세", currency: "내자", project: "", remarks: "" });
  const [lines, setLines] = useState<QuotationLine[]>([emptyLine()]); const [loading, setLoading] = useState(edit); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const readOnly = header.status === "accepted" || header.status === "rejected" || header.status === "expired";

  useEffect(() => { void Promise.all([masterDataRequest<MasterRow[]>("/api/vendors"), masterDataRequest<MasterRow[]>("/api/employees"), masterDataRequest<MasterRow[]>("/api/items")]).then(([v, e, i]) => { setVendors(v); setEmployees(e); setItems(i); }).catch((err) => setError(err instanceof Error ? err.message : "기준정보를 불러오지 못했습니다.")); }, []);
  useEffect(() => { if (!id) return; void fetchQuotation(id).then((row) => { setHeader({ quoteDate: row.quoteDate, slipNo: row.slipNo, vendorCode: row.vendorCode ?? "", vendorName: row.vendorName, managerCode: row.managerCode ?? "", managerName: row.managerName ?? "", validUntil: row.validUntil ?? "", status: row.status, taxType: row.taxType ?? "과세", currency: row.currency ?? "내자", project: row.project ?? "", remarks: row.remarks ?? "" }); setLines(row.lines?.length ? row.lines : [emptyLine()]); }).catch((err) => setError(err instanceof Error ? err.message : "견적서를 불러오지 못했습니다.")).finally(() => setLoading(false)); }, [id]);
  const calculated = useMemo(() => lines.map((line, index) => { const supply = Math.round((Number(line.qty) || 0) * (Number(line.unitPrice) || 0)); const vat = header.taxType === "과세" ? Math.round(supply * .1) : 0; return { ...line, supply, vat, total: supply + vat, sortOrder: index }; }), [lines, header.taxType]);
  const totals = useMemo(() => calculated.reduce((sum, line) => ({ qty: sum.qty + line.qty, supply: sum.supply + line.supply, vat: sum.vat + line.vat, total: sum.total + line.total }), { qty: 0, supply: 0, vat: 0, total: 0 }), [calculated]);
  const updateLine = (index: number, patch: Partial<QuotationLine>) => setLines((current) => current.map((line, i) => i === index ? { ...line, ...patch } : line));
  const selectVendor = (code: string) => { const row = vendors.find((vendor) => vendor.code === code); setHeader((current) => ({ ...current, vendorCode: code, vendorName: row?.name ?? "" })); };
  const selectEmployee = (code: string) => { const row = employees.find((employee) => employee.code === code); setHeader((current) => ({ ...current, managerCode: code, managerName: row?.name ?? "" })); };
  const selectItem = (index: number, code: string) => { const row = items.find((item) => item.code === code); updateLine(index, { itemCode: code, itemName: row?.name ?? "", spec: row?.spec ?? "", unit: row?.unit ?? "", unitPrice: row?.outboundPrice ?? 0 }); };
  async function persist(status = header.status) { setError(""); if (!header.vendorName.trim()) return setError("거래처를 선택하세요."); if (!calculated.some((line) => line.itemCode || line.itemName)) return setError("품목 행을 하나 이상 입력하세요."); setSaving(true); try { const payload: QuotationInput = { id, ...header, status, lines: calculated.filter((line) => line.itemCode || line.itemName) }; const saved = await saveQuotation(payload); if (!edit) router.replace(`/quotations/${saved.id}`); else { setHeader((current) => ({ ...current, status: saved.status, slipNo: saved.slipNo })); setLines(saved.lines ?? calculated); } } catch (err) { setError(err instanceof Error ? err.message : "저장에 실패했습니다."); } finally { setSaving(false); } }
  async function changeStatus(status: QuotationStatus) { try { const saved = await updateQuotationStatus(id!, status); setHeader((current) => ({ ...current, status: saved.status })); } catch (err) { setError(err instanceof Error ? err.message : "상태 변경에 실패했습니다."); } }
  async function remove() { if (!id || !confirm("이 견적서를 삭제할까요?")) return; try { await deleteQuotation(id); router.push("/quotations"); } catch (err) { setError(err instanceof Error ? err.message : "삭제에 실패했습니다."); } }
  if (loading) return <p className="text-sm text-muted-foreground">견적서를 불러오는 중…</p>;
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">견적서입력{edit ? " (수정)" : ""}</h2><p className="text-xs text-muted-foreground">견적 저장과 판매계획 전환은 재고 수불과 잔고를 변경하지 않습니다.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => router.push("/quotations")}>목록</Button>{edit && <Button variant="outline" onClick={remove} disabled={readOnly}>삭제</Button>}<Button onClick={() => void persist()} disabled={saving || readOnly}>저장</Button></div></div>
    {error && <p className="rounded border border-red-200 bg-red-50 p-2 text-sm text-red-700">{error}</p>}
    <section className="grid gap-3 rounded border bg-white p-4 md:grid-cols-3"><label>견적일<Input type="date" value={header.quoteDate} disabled={readOnly} onChange={(e) => setHeader({ ...header, quoteDate: e.target.value })} /></label><label>견적번호<Input value={header.slipNo || "저장 시 자동발급"} readOnly /></label><label>유효기간<Input type="date" value={header.validUntil} disabled={readOnly} onChange={(e) => setHeader({ ...header, validUntil: e.target.value })} /></label><label>거래처<select className="h-10 w-full rounded border px-2" value={header.vendorCode} disabled={readOnly} onChange={(e) => selectVendor(e.target.value)}><option value="">선택</option>{vendors.map((row) => <option key={row.code} value={row.code}>{row.code} · {row.name}</option>)}</select></label><label>담당자<select className="h-10 w-full rounded border px-2" value={header.managerCode} disabled={readOnly} onChange={(e) => selectEmployee(e.target.value)}><option value="">선택</option>{employees.map((row) => <option key={row.code} value={row.code}>{row.code} · {row.name}</option>)}</select></label><label>과세구분<select className="h-10 w-full rounded border px-2" value={header.taxType} disabled={readOnly} onChange={(e) => setHeader({ ...header, taxType: e.target.value })}>{TAX_TYPE_OPTIONS.map((value) => <option key={value}>{value}</option>)}</select></label><label>통화<select className="h-10 w-full rounded border px-2" value={header.currency} disabled={readOnly} onChange={(e) => setHeader({ ...header, currency: e.target.value })}>{CURRENCY_OPTIONS.map((value) => <option key={value}>{value}</option>)}</select></label><label>프로젝트<Input value={header.project} disabled={readOnly} onChange={(e) => setHeader({ ...header, project: e.target.value })} /></label><label>상태<Input value={header.status} readOnly /></label><label className="md:col-span-3">비고<Input value={header.remarks} disabled={readOnly} onChange={(e) => setHeader({ ...header, remarks: e.target.value })} /></label></section>
    <section className="overflow-x-auto rounded border bg-white"><table className="w-full min-w-[920px] text-sm"><thead className="bg-slate-50"><tr>{["품목", "규격", "단위", "수량", "단가", "공급가", "VAT", "합계", "비고", ""].map((name) => <th key={name} className="p-2 text-left">{name}</th>)}</tr></thead><tbody>{calculated.map((line, index) => <tr key={index} className="border-t"><td className="p-1"><select className="h-9 w-full rounded border px-1" value={line.itemCode ?? ""} disabled={readOnly} onChange={(e) => selectItem(index, e.target.value)}><option value="">선택</option>{items.map((row) => <option key={row.code} value={row.code}>{row.code} · {row.name}</option>)}</select></td><td className="p-1"><Input value={line.spec ?? ""} readOnly /></td><td className="p-1"><Input value={line.unit ?? ""} readOnly /></td><td className="p-1"><Input type="number" min="0" value={line.qty} disabled={readOnly} onChange={(e) => updateLine(index, { qty: Number(e.target.value) })} /></td><td className="p-1"><Input type="number" min="0" value={line.unitPrice} disabled={readOnly} onChange={(e) => updateLine(index, { unitPrice: Number(e.target.value) })} /></td><td className="p-1 text-right">{line.supply.toLocaleString()}</td><td className="p-1 text-right">{line.vat.toLocaleString()}</td><td className="p-1 text-right font-medium">{line.total.toLocaleString()}</td><td className="p-1"><Input value={line.extra ?? ""} disabled={readOnly} onChange={(e) => updateLine(index, { extra: e.target.value })} /></td><td className="p-1"><Button size="sm" variant="ghost" disabled={readOnly || lines.length === 1} onClick={() => setLines((current) => current.filter((_, i) => i !== index))}>삭제</Button></td></tr>)}</tbody><tfoot><tr className="border-t-2 bg-slate-50 font-semibold"><td colSpan={3} className="p-2 text-right">합계</td><td className="p-2 text-right">{totals.qty.toLocaleString()}</td><td /><td className="p-2 text-right">{totals.supply.toLocaleString()}</td><td className="p-2 text-right">{totals.vat.toLocaleString()}</td><td className="p-2 text-right">{totals.total.toLocaleString()}</td><td colSpan={2} /></tr></tfoot></table><div className="border-t p-2"><Button size="sm" variant="outline" disabled={readOnly} onClick={() => setLines((current) => [...current, emptyLine(current.length)])}>행 추가</Button></div></section>
    {edit && !readOnly && <div className="flex gap-2"><Button variant="outline" onClick={() => void changeStatus("sent")} disabled={header.status !== "draft"}>발송 처리</Button><Button onClick={() => void changeStatus("accepted")} disabled={header.status !== "sent"}>수락</Button><Button variant="destructive" onClick={() => void changeStatus("rejected")} disabled={header.status !== "sent"}>거절</Button></div>}
  </div>;
}
