"use client";
import { useEffect, useMemo, useState } from "react";
import { defaultQuotationDateRange, fetchQuotations, QUOTATION_STATUS_LABEL, type Quotation, type QuotationStatus } from "@/lib/quotations";

export function QuotationStatusDashboard() {
  const defaults = defaultQuotationDateRange(); const [from, setFrom] = useState(defaults.from); const [to, setTo] = useState(defaults.to); const [rows, setRows] = useState<Quotation[]>([]); const [error, setError] = useState("");
  async function load() { try { setRows(await fetchQuotations({ from, to })); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "현황을 불러오지 못했습니다."); } }
  useEffect(() => { void load(); }, []);
  const summary = useMemo(() => { const statuses = Object.keys(QUOTATION_STATUS_LABEL) as QuotationStatus[]; return statuses.map((status) => ({ status, count: rows.filter((row) => row.status === status).length, total: rows.filter((row) => row.status === status).reduce((sum, row) => sum + row.total, 0) })); }, [rows]);
  const expiring = useMemo(() => { const end = new Date(); end.setDate(end.getDate() + 7); const now = new Date().toISOString().slice(0, 10); const last = end.toISOString().slice(0, 10); return rows.filter((row) => row.status !== "accepted" && row.status !== "rejected" && row.validUntil && row.validUntil >= now && row.validUntil <= last); }, [rows]);
  return <div className="space-y-4"><div><h2 className="text-lg font-semibold">견적서현황</h2><p className="text-xs text-muted-foreground">KST 기준 기간별 견적 상태와 만료 예정 견적을 확인합니다.</p></div><div className="flex gap-2"><input className="h-9 rounded border px-2 text-sm" type="date" value={from} onChange={(e) => setFrom(e.target.value)} /><input className="h-9 rounded border px-2 text-sm" type="date" value={to} onChange={(e) => setTo(e.target.value)} /><button className="rounded bg-indigo-600 px-3 text-sm text-white" onClick={() => void load()}>조회</button></div>{error && <p className="text-sm text-red-700">{error}</p>}<div className="grid gap-3 md:grid-cols-3 lg:grid-cols-6"><article className="rounded border bg-white p-3"><p className="text-xs text-muted-foreground">전체 견적</p><p className="mt-1 text-lg font-semibold">{rows.length}건</p><p className="text-xs">{rows.reduce((sum, row) => sum + row.total, 0).toLocaleString()}원</p></article>{summary.map((row) => <article key={row.status} className="rounded border bg-white p-3"><p className="text-xs text-muted-foreground">{QUOTATION_STATUS_LABEL[row.status]}</p><p className="mt-1 text-lg font-semibold">{row.count}건</p><p className="text-xs">{row.total.toLocaleString()}원</p></article>)}</div><div className="grid gap-4 lg:grid-cols-2"><section className="rounded border bg-white p-4"><h3 className="font-medium">7일 이내 만료 예정 미수락 견적</h3><ul className="mt-2 divide-y text-sm">{expiring.length ? expiring.map((row) => <li className="flex justify-between py-2" key={row.id}><span>{row.slipNo} · {row.vendorName}</span><span>{row.validUntil}</span></li>) : <li className="py-4 text-muted-foreground">해당 견적이 없습니다.</li>}</ul></section><section className="rounded border bg-white p-4"><h3 className="font-medium">판매계획 전환 완료</h3><p className="mt-3 text-2xl font-semibold">{rows.filter((row) => row.convertedSalesPlanId).length}건</p></section></div></div>;
}
